### ISSUE TITLE
Bulk Download 

### ISSUE THREAD

**Issue by nyxordinal** [sinkaroid/tomoe#1]
**Describe new features you want**
It would be great if this project can support multiple doujin download at once.

**Describe the solution you'd like**
We can add support for multiple doujin ID in the CLI input parameter.

**Comment by sinkaroid** [comment]
I already planned and adding this as milestones in my testing branch, will do some unit tests and added soon.

**Comment by nyxordinal** [comment]
I tried to make a PR for this issue

**Comment by sinkaroid** [comment]
Thanks for this juicier improvements @nyxordinal 😁
