### ISSUE TITLE
Additional parameter for pdf file render

### ISSUE THREAD

**Issue by nyxordinal** [sinkaroid/tomoe#3]
**Describe new features you want**
A new parameter `--pdf` to auto choose `yes` when render pdf file option is displayed

**Additional context**
When we use bulk download, it's a hassle to manually answer `yes` to every displayed render pdf file option

**Comment by sinkaroid** [comment]
I completely understand since bulk was added, It's turn out convert prompt looks a bit clunky, will remake soon

**Comment by nyxordinal** [comment]
I'll try to make a PR for this

**Comment by sinkaroid** [comment]
Oh thanks if that so! I planning to remake soon while adding [hentaihere.com](https://hentaihere.com/) to the supported website as well
